version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${NGNIX_CONTAINER_NAME}
    restart: unless-stopped
    depends_on:
      - php-fpm
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./${APP_VOLUME_NAME}:/var/www/html
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - net
  php-fpm:
    build: 
      context: ./.docker/php
      dockerfile: Dockerfile
      args:
        - INSTALL_COMPOSER=${INSTALL_COMPOSER}
    container_name: ${APP_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ./${APP_VOLUME_NAME}:/var/www/html
      - ./.docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - ${APP_PORT}:9000
    networks:
      - net
networks: 
  net:
    driver: bridge
